# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_winner', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_name', models.CharField(max_length=255)),
                ('pokemon_type', models.CharField(max_length=255)),
                ('pokemon_level', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('pokemon_name',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('team_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'ordering': ('team_name',),
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=255)),
                ('trainer_age', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('trainer_name',),
            },
        ),
        migrations.CreateModel(
            name='PokedexEntry',
            fields=[
                ('PokedexEntry_pokemon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pokeapp.Pokemon')),
                ('PokedexEntry_decription', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='team_trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_teams', to='pokeapp.Trainer'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_pokemons', to='pokeapp.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_trainers',
            field=models.ManyToManyField(to='pokeapp.Trainer'),
        ),
    ]
