# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 20:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0004_auto_20170609_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_trainers',
            field=models.ManyToManyField(blank=True, related_name='match_trainers', to='pokeapp.Trainer'),
        ),
        migrations.AlterField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 10, 20, 6, 21, 110268, tzinfo=utc)),
        ),
    ]
