# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 21:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0005_auto_20170609_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 10, 21, 18, 16, 378432, tzinfo=utc)),
        ),
    ]
