# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 23:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0006_auto_20170609_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_pokemons', to='pokeapp.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_teams', to='pokeapp.Trainer'),
        ),
        migrations.AlterField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 10, 23, 21, 52, 538877, tzinfo=utc)),
        ),
    ]
