# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 08:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0007_auto_20170610_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokedexentry',
            old_name='PokedexEntry_decription',
            new_name='pokedexentry_decription',
        ),
        migrations.RenameField(
            model_name='pokedexentry',
            old_name='PokedexEntry_pokemon',
            new_name='pokedexentry_pokemon',
        ),
        migrations.AlterField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 11, 8, 23, 59, 261526, tzinfo=utc)),
        ),
    ]
