# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 08:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0010_auto_20170610_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='team_pokemons', to='pokeapp.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='team_trainer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_teams', to='pokeapp.Trainer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 11, 8, 33, 41, 925327, tzinfo=utc)),
        ),
    ]
